# research_agent/pdf_export.py
# Convert markdown report to professional PDF

from fpdf import FPDF
from datetime import datetime
import re, os


def _safe(text) -> str:
    """
    Final safety net - forces ANY character unsupported by FPDF's core fonts
    (em-dashes, curly quotes, ellipses, etc.) into a safe ASCII equivalent.
    Every single piece of text passed to FPDF goes through this function.
    """
    if text is None:
        return ""
    text = str(text)
    text = text.replace('—', '-').replace('–', '-')
    text = text.replace('\u2018', "'").replace('\u2019', "'")
    text = text.replace('\u201c', '"').replace('\u201d', '"')
    text = text.replace('…', '...')
    # Catch anything still left over
    text = text.encode('latin-1', errors='replace').decode('latin-1')
    return text


class ResearchReportPDF(FPDF):
    """Custom PDF class with header and footer"""

    def __init__(self, topic: str):
        super().__init__()
        self.topic = topic
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(31, 56, 100)  # dark navy
        self.rect(0, 0, 210, 18, 'F')

        self.set_font("Helvetica", "B", 11)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 5)
        self.cell(0, 8, _safe("M7RYX Research Agent"), ln=False)

        self.set_font("Helvetica", "", 8)
        self.set_xy(140, 6)
        self.cell(60, 6, _safe(datetime.now().strftime("%B %d, %Y")), align="R")

        self.set_text_color(0, 0, 0)
        self.ln(16)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10,
                  _safe(f"Generated by M7RYX Research Agent  |  Page {self.page_no()}"),
                  align="C")


def clean_markdown(text: str) -> str:
    """Strip markdown syntax, then run through the safety net"""
    text = re.sub(r'\*\*\*(.*?)\*\*\*', r'\1', text)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'\[(.*?)\]\((.*?)\)', r'\1', text)
    text = re.sub(r'^[-*]\s+', '- ', text, flags=re.MULTILINE)
    return _safe(text.strip())


def markdown_to_pdf(report_md: str,
                    topic: str,
                    output_path: str,
                    metadata: dict = None) -> str:
    pdf = ResearchReportPDF(topic)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(31, 56, 100)
    pdf.ln(8)
    pdf.multi_cell(0, 10, _safe(topic), align="C")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, _safe("AI-Generated Research Report"), align="C", ln=True)
    pdf.ln(2)

    if metadata:
        quality  = metadata.get("quality_scores", {})
        overall  = quality.get("overall", 0)
        sources  = metadata.get("pipeline_stats", {}).get("source_count", "N/A")
        depth    = metadata.get("depth", "Standard")

        pdf.set_fill_color(240, 244, 255)
        pdf.set_draw_color(102, 126, 234)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.set_x(20)
        pdf.cell(170, 8,
                 _safe(f"Quality: {overall:.0%}  |  Sources: {sources}  |  Depth: {depth}  |  "
                       f"Generated: {datetime.now().strftime('%B %d, %Y')}"),
                 border=1, align="C", fill=True, ln=True)

    pdf.ln(6)
    pdf.set_draw_color(102, 126, 234)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    lines = report_md.split("\n")
    i = 0
    while i < len(lines):
        line = _safe(lines[i].rstrip())

        if line.startswith("# ") and not line.startswith("## "):
            i += 1
            continue

        elif line.startswith("## "):
            section_title = clean_markdown(line[3:])
            pdf.ln(4)
            pdf.set_fill_color(102, 126, 234)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, _safe(f" {section_title}"), fill=True, ln=True)
            pdf.ln(3)
            pdf.set_text_color(0, 0, 0)

        elif re.match(r'^\d+\.', line):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_x(15)
            pdf.multi_cell(175, 6, clean_markdown(line))
            pdf.ln(1)

        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            text = "- " + clean_markdown(line[2:])
            pdf.set_x(15)
            pdf.multi_cell(175, 6, text)
            pdf.ln(1)

        elif line.startswith("**") and line.endswith("**"):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(31, 56, 100)
            pdf.multi_cell(0, 6, clean_markdown(line))
            pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

        elif line.startswith("---"):
            pdf.set_draw_color(200, 200, 200)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(4)

        elif line.strip():
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 6, clean_markdown(line))
            pdf.ln(1)

        else:
            pdf.ln(2)

        i += 1

    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    pdf.output(output_path)
    return output_path


def get_pdf_bytes(report_md: str, topic: str,
                  metadata: dict = None) -> bytes:
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp_path = tmp.name

    markdown_to_pdf(report_md, topic, tmp_path, metadata)

    with open(tmp_path, "rb") as f:
        pdf_bytes = f.read()

    os.unlink(tmp_path)
    return pdf_bytes