# research_agent/synthesizer.py - UPGRADED
import warnings
warnings.filterwarnings("ignore")

from utils import llm_fast, llm_strong, safe_invoke
import re, json

def extract_findings(chunks: list, topic: str, progress_callback=None) -> dict:
    """Extract grounded findings from research chunks"""
    context = "\n\n---\n\n".join([
        f"[Source {i+1}]: {c.get('title', 'unknown')[:50]}\n{c['content']}"
        for i, c in enumerate(chunks[:12])
    ])

    prompt = f"""You are a research analyst. Extract findings from these sources ONLY.
Do NOT add outside knowledge.

TOPIC: "{topic}"

SOURCES:
{context[:3500]}

Provide:
1. KEY STATISTICS (from sources - include [Source N])
2. MAIN THEMES (3-4 recurring ideas)
3. CONSENSUS (what sources agree on)
4. CONTRADICTIONS (where sources disagree)
5. GAPS (important questions not answered)"""

    findings_text = safe_invoke(llm_fast, prompt, progress_callback=progress_callback)

    # Grounding check - verify numbers appear in source text
    source_text = " ".join([c["content"] for c in chunks]).lower()
    claimed_numbers = re.findall(r'\d+(?:\.\d+)?%|\d{4,}', findings_text)
    verified = sum(1 for n in claimed_numbers 
                   if n.replace('%', '').replace(',', '') in source_text)
    grounding = verified / len(claimed_numbers) if claimed_numbers else 1.0

    return {
        "text":            findings_text,
        "grounding_score": round(grounding, 2),
        "numbers_found":   claimed_numbers[:10],
    }

def identify_themes(findings_text: str, progress_callback=None) -> list:
    """Extract structured themes as JSON"""
    prompt = f"""Extract 3-4 key themes from these findings as JSON array:
{findings_text[:1200]}

Format:
[{{\"theme\": \"name (3-5 words)\", \"description\": \"one sentence\", \"importance\": \"High/Medium/Low\"}}]

Return ONLY the JSON array. No other text."""

    try:
        resp = safe_invoke(llm_fast, prompt, progress_callback=progress_callback)
        clean = re.sub(r'```json|```', '', resp).strip()
        return json.loads(clean)
    except Exception:
        return [{"theme": "Key Research Findings", 
                 "description": "Main insights from research", 
                 "importance": "High"}]

def generate_report(findings: dict, themes: list, pipeline_result: dict, progress_callback=None) -> str:
    """Generate full structured report - uses STRONG model, this is the deliverable"""
    topic        = pipeline_result["topic"]
    sources_text = "\n".join([f"- {t or u} ({u})" for u, t in pipeline_result["sources"][:10]])
    themes_text  = "\n".join([f"- **{t['theme']}**: {t['description']}" for t in themes])

    prompt = f"""Write a professional research report on: "{topic}"

Key themes:
{themes_text}

Research findings:
{findings['text'][:2000]}

Write the complete report with these exact sections:

# {topic}

## Executive Summary
[3 sentences. Most important finding first. Include one specific statistic.]

## Key Findings
[6-8 numbered points. Each: one finding + one evidence. Include statistics where available.]

## Detailed Analysis
[3 paragraphs analyzing the main themes and their implications.]

## Knowledge Gaps
[3-4 bullet points of important unanswered questions.]

## Conclusions & Recommendations
**Conclusions:** [2-3 sentences synthesizing what was learned]
**Recommendations:**
1. [Specific action with rationale]
2. [Specific action with rationale]
3. [Specific action with rationale]

## Sources
{sources_text}

---
*Report generated by MNE Research Agent | Sources: {len(pipeline_result['sources'])} | Depth: {pipeline_result['depth']}*"""

    return safe_invoke(llm_strong, prompt, progress_callback=progress_callback)

def quality_check(report: str, topic: str, progress_callback=None) -> dict:
    """Score report quality across four dimensions"""
    prompt = f"""Score this research report:
Topic: "{topic}"
Report excerpt: {report[:1800]}

JSON only:
{{
  "relevance": 0.0-1.0,
  "specificity": 0.0-1.0,
  "structure": 0.0-1.0,
  "actionability": 0.0-1.0,
  "overall": 0.0-1.0,
  "weakest_section": "section name",
  "improvement": "one specific sentence"
}}"""

    try:
        resp = safe_invoke(llm_fast, prompt, progress_callback=progress_callback)
        clean = re.sub(r'```json|```', '', resp).strip()
        return json.loads(clean)
    except Exception:
        return {"relevance": 0.7, "specificity": 0.6, "structure": 0.7, 
                "actionability": 0.6, "overall": 0.65, "weakest_section": "Analysis", 
                "improvement": "Add more specific statistics."}

def improve_weak_section(report: str, quality: dict, topic: str, progress_callback=None) -> str:
    """Rewrite only the weakest section - uses STRONG model since it edits the deliverable"""
    weak    = quality.get("weakest_section", "")
    suggest = quality.get("improvement", "")

    if not weak or f"## {weak}" not in report:
        return report

    prompt = f"""Improve the '{weak}' section of this research report.
Topic: {topic}
Improvement needed: {suggest}

Current section content (from '## {weak}' to next '##'):
{report[report.find(f'## {weak}'):report.find('## ', report.find(f'## {weak}') + 5)]}

Rewrite this section to be more specific and actionable.
Return ONLY the improved section content (no header line)."""

    improved_content = safe_invoke(llm_strong, prompt, progress_callback=progress_callback)
    old_section_start = report.find(f"## {weak}")
    next_section      = report.find("\n## ", old_section_start + 5)

    if next_section > 0:
        return (report[:old_section_start] 
                + f"## {weak}\n\n{improved_content}\n\n" 
                + report[next_section:])
    return report

def run_synthesis(pipeline_result: dict, progress_callback=None) -> dict:
    """Complete synthesis pipeline with grounding + surgical retry"""
    def update(msg):
        if progress_callback:
            progress_callback(msg)

    chunks = pipeline_result["chunks"]
    topic  = pipeline_result["topic"]

    update("🧠 Extracting key findings...")
    findings = extract_findings(chunks, topic, progress_callback)

    if findings["grounding_score"] < 0.4:
        update("⚠️ Low grounding detected - using conservative synthesis...")

    update("🏷️ Identifying themes...")
    themes = identify_themes(findings["text"], progress_callback)

    update("📝 Writing report...")
    report = generate_report(findings, themes, pipeline_result, progress_callback)

    update("✅ Quality checking...")
    quality = quality_check(report, topic, progress_callback)

    if quality.get("overall", 0) < 0.65:
        update(f"🔄 Improving {quality.get('weakest_section', 'report')}...")
        report = improve_weak_section(report, quality, topic, progress_callback)
        quality = quality_check(report, topic, progress_callback)

    return {
        "report":         report,
        "findings":       findings,
        "themes":         themes,
        "quality_scores": quality,
        "topic":          topic,
    }

